### ISSUE TITLE
before_create may not be called before create

### ISSUE THREAD

**Issue by rbriank** [citrus/crudify#1]
I'm just looking at the code for create and noticed that if the object is valid it will have already been created when the before_create hook is called.

Would it make sense to change the first create to a new, then call before_create, then valid? and then save?

**Comment by citrus** [comment]
Thanks for pointing this out! I'm not sure how that slipped by me.. I must have meant to initialize a new object then validate and save... I'll push an update shortly :)

**Comment by rbriank** [comment]
Cool.  I'm working with refinery too.  I'd like to see it use the gem.  With
all the hooks, it should be able to handle it.  i put in a request, but
they're trying to get 1.0 out the door so I doubt it will be before that.

B

**Comment by citrus** [comment]
updates have been pushed to github and 0.0.6 has been released on rubygems :)

thanks again for bringing this to my attention!

**Comment by rbriank** [comment]
I'd like to add you to my professional network on LinkedIn.
- Brian

Brian  Kierstead
Information Technology and Services Professional
Ontario, Canada

Confirm that you know Brian  Kierstead:
https://www.linkedin.com/e/s3n0cw-gui8q7et-45/isd/4773961256/3YOYdPgI/?hs=false&tok=1H9COMwiSJM4Y1

## 

You are receiving Invitation to Connect emails. Click to unsubscribe:
http://www.linkedin.com/e/s3n0cw-gui8q7et-45/q3QKptP3H3Rt4HMY4e9LHzc6zffppF53Fsgi_d3W2lNypo008ccnmu3YtBfChuSULQgVq7Y6v4fJvU0AHPRVq7JG-ysh-uS6CKRGCz/goo/reply%2Bi-900800-5fb0d9042fe07df675de012af24f7086f0cf6ed1%40reply%2Egithub%2Ecom/20061/I1659929324_1/?hs=false&tok=1ppXaxw5aJM4Y1

(c) 2011 LinkedIn Corporation. 2029 Stierlin Ct, Mountain View, CA 94043, USA.

**Comment by citrus** [comment]
sure, why not..
