### ISSUE TITLE
Add README warning that this plugin isn't 100% consistent with Refinery

### ISSUE THREAD

**Issue by machty** [citrus/crudify#6]
I just wasted an hour trying to get a `before_update` hook to work on a Refinery project, only to find that their version of `crudify` doesn't work. I know this isn't exactly your responsibility, but since you mention the origins of this plugin, it might be a good idea to put a little blurb saying that this version of `crudify` is a souped up version of the one that comes with Refinery, and that there might be some features in this version that aren't present in vanilla refinery.

**Comment by parndt** [comment]
If you can, please open a pull request to add the requested statement :-)

Refinery unfortunately hasn't managed to migrate over yet.  That's also something that could be helped with if you're keen!

Thanks.
